# Generated by Django 3.0.6 on 2020-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_auto_20200512_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
